package bidrl

import "github.com/hbaldwin98/control-center/host"

func publishedEvents() []host.EventSpec {
	return []host.EventSpec{
		event("alert", "A new watchlist finding, or a favorited lot closing within 24 hours. Matched by the default plugin-alert rule.",
			field("title", "string", "Short headline."),
			field("body", "string", "What happened, ready to send."),
			field("watchlistId", "string", "Watchlist that produced findings, when this is a finding alert."),
			field("count", "number", "How many new findings, when this is a finding alert."),
			field("lotId", "string", "The lot, when this is an ending-soon alert."),
			field("endsAt", "string", "When that lot closes."),
		),
		event("finding.created", "A watchlist produced new lots that still need a decision.",
			field("watchlistId", "string", "The watchlist that matched."),
			field("count", "number", "How many new findings this run."),
		),
		event("finding.decided", "Someone accepted or rejected a finding.",
			field("findingId", "string", "The finding that was decided."),
			field("lotId", "string", "The lot on that finding."),
			field("state", "string", "accepted or rejected."),
		),
		event("watch.completed", "One watchlist finished matching against stored lots.",
			field("watchlistId", "string", "The watchlist that ran."),
			field("name", "string", "Display name of the watchlist."),
			field("findings", "number", "New findings this run."),
		),
		event("sweep.completed", "A scheduled sweep finished collecting auctions.",
			field("auctions", "number", "Auctions collected."),
			field("lots", "number", "Lots stored."),
		),
		event("sweep.throttled", "BidRL refused requests; the sweep is latched until a later tick.",
			field("until", "string", "RFC3339Nano time after which the next sweep may try again."),
		),
		event("match.completed", "Every enabled watchlist finished a match pass.",
			field("findings", "number", "New findings across watchlists."),
			field("watchlists", "number", "How many watchlists ran."),
			field("failed", "number", "How many watchlists errored."),
		),
		event("auction.collected", "An auction the sweep had not stored before was collected: its lots are now stored.",
			field("auctionId", "string", "The auction."),
			field("url", "string", "Canonical auction URL."),
			field("title", "string", "Auction title."),
			field("lotCount", "number", "Lots stored."),
			field("affiliateId", "string", "BidRL location the auction belongs to."),
			field("affiliateName", "string", "Display name of that location."),
			field("city", "string", "City of that location."),
			field("endsAt", "string", "When the auction closes."),
		),
		event("scan.completed", "Vision, enrichment, and pricing for one auction finished.",
			field("auctionId", "string", "The auction that was scanned."),
		),
		event("bids.refreshed", "Live catalog bids were written onto stored lots.",
			field("auctionId", "string", "The auction whose bids were refreshed."),
			field("at", "string", "RFC3339Nano time of the refresh."),
			field("lots", "number", "Lots whose bid changed."),
			field("source", "string", "Where the bids came from."),
		),
		event("lot.enriched", "Photographs for one lot were stored.",
			field("lotId", "string", "The lot."),
			field("auctionId", "string", "The auction it belongs to."),
		),
		event("lot.analyzed", "Vision identified what a lot's photographs show.",
			field("lotId", "string", "The lot."),
			field("auctionId", "string", "The auction it belongs to."),
			field("title", "string", "Auction title as listed."),
			field("identification", "string", "What the model said the photographs show."),
			field("basis", "string", "How confident the identification is."),
			field("bucket", "string", "priced, needs_price, or rejected."),
			field("category", "string", "Closed category the model assigned."),
		),
		event("lot.priced", "A cited marketplace price was written for a lot.",
			field("lotId", "string", "The lot."),
			field("auctionId", "string", "The auction it belongs to."),
			field("title", "string", "Auction title as listed."),
			field("priceCents", "number", "Cited price in cents."),
			field("bidCents", "number", "Current bid in cents."),
			field("kind", "string", "How the price was obtained."),
			field("sourceUrl", "string", "Page the price was cited from."),
			field("sourceClass", "string", "What kind of site that was."),
			field("reusedFromLotId", "string", "Earlier lot the price was copied from, if any."),
		),
		event("deal_found", "The cited price is enough of a discount relative to the current bid to be interesting.",
			field("lotId", "string", "The lot."),
			field("auctionId", "string", "The auction it belongs to."),
			field("title", "string", "Auction title as listed."),
			field("priceCents", "number", "Cited price in cents."),
			field("bidCents", "number", "Current bid in cents."),
			field("kind", "string", "How the price was obtained."),
			field("sourceUrl", "string", "Page the price was cited from."),
			field("sourceClass", "string", "What kind of site that was."),
			field("reusedFromLotId", "string", "Earlier lot the price was copied from, if any."),
		),
		event("search.completed", "A title search against stored lots finished.",
			field("query", "string", "What was searched."),
			field("scope", "string", "prefer, only, or all."),
			field("hits", "number", "Lots returned."),
		),
		event("intent.completed", "An intent search ranked stored lots by meaning.",
			field("query", "string", "The stated intent."),
			field("hits", "number", "Lots kept."),
			field("scanned", "number", "Lots considered."),
			field("skipped", "number", "Lots excluded by free rules."),
		),
		event("sites.discovered", "Open SITES auctions were listed from BidRL's locations menu.",
			field("auctionCount", "number", "Auctions found."),
		),
		event("expired.cleaned", "Closed auctions and their lots were removed.",
			field("auctions", "number", "Auctions removed."),
			field("lots", "number", "Lots removed."),
			field("sites", "number", "SITES rows removed."),
		),
	}
}

func event(typ, purpose string, fields ...host.EventField) host.EventSpec {
	return host.EventSpec{Type: typ, Purpose: purpose, Fields: fields}
}

func field(name, typ, purpose string) host.EventField {
	return host.EventField{Name: name, Type: typ, Purpose: purpose}
}
